// <auto-generated />
using System;
using KodiNet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KodiNet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KodiNet.Domain.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("app_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full access (Pi management, transfers, deletion)",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pi monitoring, file transfers",
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Read-only — view the status of the Pi",
                            Name = "Viewer"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sole owner — non-revocable admin rights, cannot be configured via the UI",
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("app_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "Mail:From",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8242),
                            Value = ""
                        },
                        new
                        {
                            Key = "Mail:FromName",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8247),
                            Value = "Kodinet"
                        },
                        new
                        {
                            Key = "Mail:SmtpHost",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8248),
                            Value = ""
                        },
                        new
                        {
                            Key = "Mail:SmtpPort",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8250),
                            Value = "587"
                        },
                        new
                        {
                            Key = "Mail:EnableSsl",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8251),
                            Value = "true"
                        },
                        new
                        {
                            Key = "Mail:Username",
                            IsSensitive = false,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8252),
                            Value = ""
                        },
                        new
                        {
                            Key = "Mail:Password",
                            IsSensitive = true,
                            UpdatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8253),
                            Value = ""
                        });
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.AppTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DarkPaletteJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LightPaletteJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SwatchColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("app_themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8417),
                            DarkPaletteJson = "{\r\n  \"primary\": \"#e08090\",\r\n  \"primaryDarken\": \"#f0a8b4\",\r\n  \"secondary\": \"#7ab89a\",\r\n  \"secondaryDarken\": \"#9acdb5\",\r\n  \"background\": \"#1a0d10\",\r\n  \"surface\": \"#2b1419\",\r\n  \"appbarBackground\": \"#220e13\",\r\n  \"appbarText\": \"#fce8eb\",\r\n  \"textPrimary\": \"#fce8eb\",\r\n  \"textSecondary\": \"#c09090\",\r\n  \"divider\": \"#4a2530\",\r\n  \"error\": \"#ef9a9a\",\r\n  \"success\": \"#a5d6a7\",\r\n  \"warning\": \"#ffcc80\",\r\n  \"info\": \"#e08090\"\r\n}",
                            IsSystem = true,
                            LightPaletteJson = "{\r\n  \"primary\": \"#9D344B\",\r\n  \"primaryDarken\": \"#7a2539\",\r\n  \"secondary\": \"#4A7C5E\",\r\n  \"secondaryDarken\": \"#3a6149\",\r\n  \"background\": \"#fdf5f6\",\r\n  \"surface\": \"#ffffff\",\r\n  \"appbarBackground\": \"#9D344B\",\r\n  \"appbarText\": \"#ffffff\",\r\n  \"textPrimary\": \"#3a1520\",\r\n  \"textSecondary\": \"#9a7580\",\r\n  \"divider\": \"#f0d5da\",\r\n  \"error\": \"#b71c1c\",\r\n  \"success\": \"#4A7C5E\",\r\n  \"warning\": \"#e65100\",\r\n  \"info\": \"#7a2539\"\r\n}",
                            Name = "Ruby",
                            SwatchColor = "#9D344B"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8422),
                            DarkPaletteJson = "{\r\n  \"primary\": \"#6aafc5\",\r\n  \"primaryDarken\": \"#90c8d8\",\r\n  \"secondary\": \"#70b8c8\",\r\n  \"secondaryDarken\": \"#98d0dc\",\r\n  \"background\": \"#080f14\",\r\n  \"surface\": \"#101e28\",\r\n  \"appbarBackground\": \"#0d1a22\",\r\n  \"appbarText\": \"#d8eef5\",\r\n  \"textPrimary\": \"#d8eef5\",\r\n  \"textSecondary\": \"#6090a8\",\r\n  \"divider\": \"#1a3a50\",\r\n  \"error\": \"#ef9a9a\",\r\n  \"success\": \"#a5d6a7\",\r\n  \"warning\": \"#ffcc80\",\r\n  \"info\": \"#6aafc5\"\r\n}",
                            IsSystem = true,
                            LightPaletteJson = "{\r\n  \"primary\": \"#28546C\",\r\n  \"primaryDarken\": \"#1a3d52\",\r\n  \"secondary\": \"#3A8FA3\",\r\n  \"secondaryDarken\": \"#2d7388\",\r\n  \"background\": \"#eef5f8\",\r\n  \"surface\": \"#ffffff\",\r\n  \"appbarBackground\": \"#28546C\",\r\n  \"appbarText\": \"#ffffff\",\r\n  \"textPrimary\": \"#0e2030\",\r\n  \"textSecondary\": \"#5a7a8a\",\r\n  \"divider\": \"#c8dfe8\",\r\n  \"error\": \"#c62828\",\r\n  \"success\": \"#2e7d32\",\r\n  \"warning\": \"#ef6c00\",\r\n  \"info\": \"#1a3d52\"\r\n}",
                            Name = "Ocean",
                            SwatchColor = "#28546C"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8424),
                            DarkPaletteJson = "{\r\n  \"primary\": \"#d4956a\",\r\n  \"primaryDarken\": \"#e8b898\",\r\n  \"secondary\": \"#aab870\",\r\n  \"secondaryDarken\": \"#c8d090\",\r\n  \"background\": \"#140e06\",\r\n  \"surface\": \"#221608\",\r\n  \"appbarBackground\": \"#1c1205\",\r\n  \"appbarText\": \"#faebd7\",\r\n  \"textPrimary\": \"#faebd7\",\r\n  \"textSecondary\": \"#b09070\",\r\n  \"divider\": \"#3c2810\",\r\n  \"error\": \"#ef9a9a\",\r\n  \"success\": \"#a5d6a7\",\r\n  \"warning\": \"#ffcc80\",\r\n  \"info\": \"#d4956a\"\r\n}",
                            IsSystem = true,
                            LightPaletteJson = "{\r\n  \"primary\": \"#AA6C39\",\r\n  \"primaryDarken\": \"#8a5228\",\r\n  \"secondary\": \"#7A8A3A\",\r\n  \"secondaryDarken\": \"#606e2c\",\r\n  \"background\": \"#faf4ec\",\r\n  \"surface\": \"#ffffff\",\r\n  \"appbarBackground\": \"#AA6C39\",\r\n  \"appbarText\": \"#ffffff\",\r\n  \"textPrimary\": \"#2e1c0a\",\r\n  \"textSecondary\": \"#8a6a50\",\r\n  \"divider\": \"#e8d8c0\",\r\n  \"error\": \"#c62828\",\r\n  \"success\": \"#558b2f\",\r\n  \"warning\": \"#e65100\",\r\n  \"info\": \"#8a5228\"\r\n}",
                            Name = "Amber",
                            SwatchColor = "#AA6C39"
                        });
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CronNotificationsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MicrosoftOid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MicrosoftOid")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.CronJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("app_cron_jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8459),
                            Description = "Restart any inactive Kodi players and play the video folder on a loop.",
                            IsEnabled = false,
                            Name = "KodiRestarter",
                            Schedule = "0 6-16 * * *"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 30, 14, 29, 1, 769, DateTimeKind.Utc).AddTicks(8465),
                            Description = "Reboot the LibreELEC system on all the Pi devices in the list.",
                            IsEnabled = false,
                            Name = "KodiRebooter",
                            Schedule = "50 5 * * *"
                        });
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.CronJobExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CronJobId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CronJobId");

                    b.ToTable("app_cron_executions", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("establishments", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.RaspberryPi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("KodiPasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KodiPort")
                        .HasColumnType("int");

                    b.Property<string>("KodiUserEncrypted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SshPasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SshPort")
                        .HasColumnType("int");

                    b.Property<string>("SshUserEncrypted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoFolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("raspberry_pis", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int?>("SelectedThemeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SelectedThemeId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "AppRoleId");

                    b.HasIndex("AppRoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.CronJobExecution", b =>
                {
                    b.HasOne("KodiNet.Domain.Entities.CronJob", "CronJob")
                        .WithMany("Executions")
                        .HasForeignKey("CronJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronJob");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.RaspberryPi", b =>
                {
                    b.HasOne("KodiNet.Domain.Entities.Establishment", "Establishment")
                        .WithMany("RaspberryPis")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("KodiNet.Domain.Entities.AppUser", "AppUser")
                        .WithOne()
                        .HasForeignKey("KodiNet.Domain.Entities.UserPreference", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodiNet.Domain.Entities.AppTheme", "SelectedTheme")
                        .WithMany()
                        .HasForeignKey("SelectedThemeId");

                    b.Navigation("AppUser");

                    b.Navigation("SelectedTheme");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("KodiNet.Domain.Entities.AppRole", "AppRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KodiNet.Domain.Entities.AppUser", "AppUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.CronJob", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("KodiNet.Domain.Entities.Establishment", b =>
                {
                    b.Navigation("RaspberryPis");
                });
#pragma warning restore 612, 618
        }
    }
}
